#!/usr/bin/env php
<?php
/**
 * Zookeeper Online
 *
 * @author Jim Mason <jmason@ibinx.com>
 * @copyright Copyright (C) 1997-2023 Jim Mason <jmason@ibinx.com>
 * @link https://zookeeper.ibinx.com/
 * @license GPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License,
 * version 3, along with this program.  If not, see
 * http://www.gnu.org/licenses/
 *
 */

chdir(__DIR__);

if($argc == 1) {
    echo "Usage: zk TARGET [NAME=VALUE...]\n";
    exit -1;
}

/**
 * parse out zero or more NAME=VALUE pairs from the argument list
 */
$_REQUEST = [];
foreach($argv as $arg) {
    $tuple = explode('=', $arg);
    if(sizeof($tuple) == 2)
        $_REQUEST[$tuple[0]] = $tuple[1];
}

/**
 * by default, TARGET is the first argument, unless explicitly specified
 */
if(!array_key_exists('target', $_REQUEST)) {
    $tuple = explode(':', $argv[1]);
    $_REQUEST['target'] = $tuple[0];
    if(count($tuple) > 1 && !array_key_exists('action', $_REQUEST))
        $_REQUEST['action'] = $tuple[1];
}

require('index.php');
